apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: v1
kind: Namespace
metadata:
  name: outline
---
apiVersion: v1
kind: Namespace
metadata:
  name: vpn
