transport:
  $type: tcpudp
  tcp:
    $type: shadowsocks
    endpoint:
      $type: websocket
      url: "wss://keys.example.com/GLOBAL/tcp"
    cipher: "2022-blake3-chacha20-poly1305"
    secret: "cGFzc3dvcmQtMzItYnl0ZXMtZm9yLTIwMjIta2V5cw=="
  udp:
    $type: shadowsocks
    endpoint:
      $type: websocket
      url: "wss://keys.example.com/GLOBAL/udp"
    cipher: "2022-blake3-chacha20-poly1305"
    secret: "cGFzc3dvcmQtMzItYnl0ZXMtZm9yLTIwMjIta2V5cw=="
