transport:
  $type: tcpudp
  tcp:
    $type: shadowsocks
    endpoint:
      $type: websocket
      url: "wss://keys.example.com/GLOBAL/tcp"
    cipher: "chacha20-ietf-poly1305"
    secret: "pw-ss-only"
  udp:
    $type: shadowsocks
    endpoint:
      $type: websocket
      url: "wss://keys.example.com/GLOBAL/udp"
    cipher: "chacha20-ietf-poly1305"
    secret: "pw-ss-only"
