import Foundation

/// Renders a `ServerProfile` into a valid TOML configuration for `outline-ws-rust`.
public enum ConfigGenerator {

    /// Generates a complete TOML config for running `outline-ws-rust` in the selected mode.
    public static func generateConfig(
        for profile: ServerProfile,
        mode: ProxyMode = .socks5,
        socksPort: Int = 1080
    ) -> String {
        // Subscriptions return their cached TOML directly if available
        if profile.isSubscription && !profile.cachedToml.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return applyModeConfiguration(to: profile.cachedToml, mode: mode, socksPort: socksPort)
        }

        // Raw override escape hatch
        if !profile.rawTomlOverride.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return applyModeConfiguration(to: profile.rawTomlOverride, mode: mode, socksPort: socksPort)
        }

        var toml = """
        # Generated by Outline Proxy for macOS
        [socks5]
        listen = "127.0.0.1:\(socksPort)"

        """

        if mode == .tun {
            toml += """
            [tun]
            path = "utun"
            mtu = 1500
            sniff_quic = true

            [tun.tcp]
            sniffing = true

            """
        }

        toml += """
        [h2]
        keepalive_interval_secs = 60
        keepalive_timeout_secs = 20

        [quic]
        keepalive_secs = 25
        idle_timeout_secs = 60

        [[outline.uplinks]]
        name = "\(escapeToml(profile.name.isEmpty ? "primary" : profile.name))"
        transport = "\(profile.transport)"
        link = "\(escapeToml(profile.link))"

        [padding]
        enabled = \(profile.paddingEnabled)

        """
        return toml
    }

    /// Legacy alias for SOCKS5 mode config generation.
    public static func generateSocks5Config(
        for profile: ServerProfile,
        socksPort: Int = 1080
    ) -> String {
        generateConfig(for: profile, mode: .socks5, socksPort: socksPort)
    }

    private static func applyModeConfiguration(to toml: String, mode: ProxyMode, socksPort: Int) -> String {
        let lines = toml.components(separatedBy: .newlines)

        if mode == .socks5 {
            // Strip any [tun] and [tun.*] sections completely so it doesn't attempt to open utun without root
            var filtered: [String] = []
            var inTunSection = false
            for line in lines {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.hasPrefix("[tun") {
                    inTunSection = true
                    continue
                } else if trimmed.hasPrefix("[") && !trimmed.hasPrefix("[tun") {
                    inTunSection = false
                }
                if !inTunSection {
                    filtered.append(line)
                }
            }
            var result = filtered.joined(separator: "\n")
            if !result.contains("[socks5]") {
                result = """
                [socks5]
                listen = "127.0.0.1:\(socksPort)"

                """ + result
            }
            return result
        } else {
            // TUN mode: replace Android "vpn" placeholder with macOS native "utun"
            var modified: [String] = []
            for line in lines {
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                if trimmed.hasPrefix("path =") && (trimmed.contains("\"vpn\"") || trimmed.contains("'vpn'")) {
                    modified.append("path = \"utun\"")
                } else {
                    modified.append(line)
                }
            }
            var result = modified.joined(separator: "\n")
            if !result.contains("[tun]") {
                result += """


                [tun]
                path = "utun"
                mtu = 1500
                sniff_quic = true

                [tun.tcp]
                sniffing = true
                """
            }
            if !result.contains("[socks5]") {
                result = """
                [socks5]
                listen = "127.0.0.1:\(socksPort)"

                """ + result
            }
            return result
        }
    }

    private static func escapeToml(_ str: String) -> String {
        str.replacingOccurrences(of: "\\", with: "\\\\")
           .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
