#!/bin/sh
# Keep ndppd's proxied prefix in sync with the interface's current RA-advertised
# global /64.
#
# Why: the `outbound_ipv6_prefix_interface` source (server and client) binds
# upstream/direct sockets to *random* addresses across the whole /64 with
# IPV6_FREEBIND. On a SLAAC segment the upstream router (e.g. a Keenetic that
# received the prefix via DHCPv6-PD and re-advertises it into the LAN) only
# sends return traffic to an address once it learns, via NDP, that the address
# lives on this host. ndppd answers those neighbour solicitations for the whole
# prefix. But the prefix is dynamic — it changes when the provider link
# reconnects — so this script re-derives it and rewrites ndppd.conf on change.
#
# Run it from the systemd timer in this directory (every ~30s). Idempotent:
# exits without touching anything when the prefix is unchanged.
#
# Env overrides: IFACE (default enp1s0), CONF (/etc/ndppd.conf),
# STATE (/run/ndppd-prefix.state).
set -eu

IFACE="${IFACE:-enp1s0}"
CONF="${CONF:-/etc/ndppd.conf}"
STATE="${STATE:-/run/ndppd-prefix.state}"

# Current global /64 from the RA route. Skip ULA (fc/fd) and link-local (fe80).
pfx=$(ip -6 route show proto ra dev "$IFACE" 2>/dev/null \
      | awk '$1 ~ /\/64$/ && $1 !~ /^f[cde]/ {print $1; exit}')
if [ -z "$pfx" ]; then
    echo "ndppd-prefix-sync: no global RA /64 on $IFACE yet" >&2
    exit 0
fi

if [ "$pfx" = "$(cat "$STATE" 2>/dev/null || true)" ]; then
    exit 0   # unchanged — nothing to do
fi

cat > "$CONF" <<EOF
# Auto-generated by ndppd-prefix-sync.sh — do not edit by hand.
route-ttl 30000
proxy $IFACE {
    router no
    timeout 500
    ttl 30000
    rule $pfx {
        static
    }
}
EOF

echo "$pfx" > "$STATE"
# Reload if supported, else restart, so the new prefix takes effect.
systemctl reload ndppd 2>/dev/null || systemctl restart ndppd
logger -t ndppd-prefix-sync "synced ndppd proxy prefix -> $pfx" 2>/dev/null || true
